# Generated by Django 5.2.1 on 2025-06-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customerName", models.CharField(max_length=100)),
                ("mobileNumber", models.CharField(max_length=15)),
                (
                    "buildType",
                    models.CharField(
                        choices=[("Offer", "Offer"), ("Normal", "Normal")],
                        max_length=20,
                    ),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[("In-Person", "In-Person"), ("Shipment", "Shipment")],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "qualityCheckBy",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qualityCheckDate", models.DateTimeField(blank=True, null=True)),
                ("eta", models.DateField(blank=True, null=True)),
                ("deadline", models.DateField()),
                ("orderDate", models.DateField()),
                ("enquiryId", models.CharField(max_length=50)),
                ("paymentDone", models.DecimalField(decimal_places=2, max_digits=10)),
                ("totalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balancePayment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("adminName", models.CharField(max_length=100)),
                ("builder", models.CharField(blank=True, max_length=100, null=True)),
                ("tester", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "currentStage",
                    models.CharField(
                        choices=[
                            ("Components Pending", "Components Pending"),
                            ("Components Assigned", "Components Assigned"),
                            ("Build Started", "Build Started"),
                            ("Build Completed", "Build Completed"),
                            ("Testing Started", "Testing Started"),
                            ("Test Completed", "Test Completed"),
                            ("Ready for Shipment", "Ready for Shipment"),
                            ("Shipped", "Shipped"),
                        ],
                        default="Components Pending",
                        max_length=50,
                    ),
                ),
                (
                    "status_updater",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("builderAssignedDate", models.DateTimeField(blank=True, null=True)),
                ("testerAssignedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "shipmentStatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("In Transit", "In Transit"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Pending",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "trackingNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Sales Team", "Sales Team"),
                            ("Service Team", "Service Team"),
                            ("Supervisor", "Supervisor"),
                            ("Hardware Engineer TL", "Hardware Engineer TL"),
                            ("Hardware Engineer Team", "Hardware Engineer Team"),
                            ("Accounts Team", "Accounts Team"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testing", models.TextField()),
                ("chipset_drivers", models.TextField()),
                ("graphics_drivers", models.TextField()),
                ("bios_firmware_version", models.TextField()),
                ("network_drivers", models.TextField()),
                ("wifi", models.TextField()),
                ("bluetooth", models.TextField()),
                ("storage_partitioning", models.TextField()),
                ("lan_detection", models.TextField()),
                ("usb_detection", models.TextField()),
                ("headphone", models.TextField()),
                ("admin_name", models.TextField()),
                ("resizable_bar", models.TextField()),
                ("ram_xmp_profile", models.TextField()),
                ("prime95_test", models.TextField()),
                ("operating_system", models.TextField()),
                ("antivirus_activation", models.TextField()),
                ("basic_software_installation", models.TextField()),
                ("cinebench_r23_single_core_stock", models.TextField()),
                ("cinebench_r23_multicore_stock", models.TextField()),
                ("cpu_temperature_idle_load_stress", models.TextField()),
                ("gpu_temperature_idle_load_stress", models.TextField()),
                ("game1AvgFps", models.TextField()),
                ("game2AvgFps", models.TextField()),
                ("premiere_render_time", models.TextField()),
                ("date_of_benchmark", models.DateField()),
                ("build_by", models.TextField()),
                ("tested_by", models.TextField()),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="app.build",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "serialNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eta", models.DateField(blank=True, null=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="app.build",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_raised", models.BooleanField(default=False)),
                ("sales_order_raised", models.BooleanField(default=False)),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_status",
                        to="app.build",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("updated_by", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[("advance", "Advance"), ("rollback", "Rollback")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("rollback_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="app.build",
                    ),
                ),
            ],
        ),
    ]
