# Generated by Django 5.2.1 on 2025-06-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_chipset_drivers_checklist_chipsetdrivers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="admin_name",
            new_name="adminName",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="antivirus_activation",
            new_name="antivirusActivation",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="basic_software_installation",
            new_name="basicSoftwareInstallation",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="bios_firmware_version",
            new_name="biosFirmwareVersion",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="build_by",
            new_name="buildBy",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="cinebench_r23_multicore_stock",
            new_name="cinebenchR23MulticoreStock",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="cinebench_r23_single_core_stock",
            new_name="cinebenchR23SingleCoreStock",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="cpu_temperature_idle_load_stress",
            new_name="cpuTemperatureIdleLoadStress",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="date_of_benchmark",
            new_name="dateOfBenchmark",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="gpu_temperature_idle_load_stress",
            new_name="gpuTemperatureIdleLoadStress",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="lan_detection",
            new_name="lanDetection",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="network_drivers",
            new_name="networkDrivers",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="operating_system",
            new_name="operatingSystem",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="premiere_render_time",
            new_name="premiereRenderTime",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="prime95_test",
            new_name="prime95Test",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="ram_xmp_profile",
            new_name="ramXmpProfile",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="resizable_bar",
            new_name="resizableBar",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="storage_partitioning",
            new_name="storagePartitioning",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="tested_by",
            new_name="testedBy",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="usb_detection",
            new_name="usbDetection",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="additional_notes",
        ),
    ]
