# Generated by Django 5.2.1 on 2025-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_admin_name_checklist_adminname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
