# Generated by Django 5.2.1 on 2025-06-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_build_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="type",
        ),
    ]
