# Generated by Django 5.2.1 on 2025-06-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_component_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="price",
            field=models.IntegerField(default=10000, max_length=7),
            preserve_default=False,
        ),
    ]
