# Generated by Django 5.2.1 on 2025-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_component_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="price",
            field=models.IntegerField(),
        ),
    ]
