# Generated by Django 5.2.1 on 2025-06-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_component_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="dateOfFinalPayment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="build",
            name="dateOfInitialPayment",
            field=models.DateField(blank=True, null=True),
        ),
    ]
